<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

  <!-- Xacro helpers, namespaced to prevent name collisions -->
  <xacro:include filename="helper_macros.xacro"/>

  <!-- Robotiq EPick + Suction Cup with optional extension

       Creates the following kinematic chain of (prefixed) links:
         epick_base_link
         epick_body

       The dimensions of the suction cup and extension are configurable, the TCP can be
       adjusted (moved into the suction cup) for tuning the contact stroke.

       parent: the link used as parent for the EPick base
       origin_*: xyz/rpy offsets of the base link
       prefix: placed before all link and joint names

       Note: '^' makes macro params default to parent properties
  -->
  <xacro:macro name="epick_body"
               params="parent:=^
                       origin_xyz:=^|'0 0 0'
                       origin_rpy:=^|'0 0 0'
                       prefix:=^|''">

    <!-- Constants -->
    <xacro:property name="base_link" value="${prefix}epick_base_link"/>
    <xacro:property name="body_link" value="${prefix}epick_body" scope="parent"/>
    <xacro:property name="body_length" value="0.1023" scope="parent"/>
    <xacro:property name="body_color" value="0.25 0.25 0.25 1" scope="parent"/>
    <xacro:property name="body_collision_radius" value="0.044"/>

    <!-- Base Link -->
    <link name="${base_link}"/>
    <xacro:joint parent="${parent}"
                 child="${base_link}"
                 xyz="${origin_xyz}"
                 rpy="${origin_rpy}"/>

    <!-- EPick Body -->
    <link name="${body_link}">
      <visual>
        <!-- Shifted backwards since the mesh origin is at the base end -->
        <origin xyz="0 0 ${-body_length / 2}" rpy="0 0 0"/>
        <geometry>
          <mesh filename="package://robot_description/meshes/visual/epick_body.stl"
            scale="0.001 0.001 0.001"/>
        </geometry>
        <material name="epick_gray">
          <color rgba="${body_color}"/>
        </material>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <cylinder radius="${body_collision_radius}" length="${body_length}"/>
        </geometry>
      </collision>
    </link>

    <xacro:joint parent="${base_link}"
                 child="${body_link}"
                 xyz="0 0 ${body_length / 2}"
                 rpy="0 0 0"/>

  </xacro:macro>
</robot>
